name: Build README

on:
  push:
    branches:
      - 'source'
  workflow_dispatch:
  schedule:
    - cron:  '11 */2 * * *'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build README
        run: |
          curl -X GET "$TIME_API_URL" -H "Authorization: Basic $TIME_API_KEY" \
            | jq -r '.languages[] | [.key, .total] | @csv' \
            | sed 's/"//g' \
            | python3 process.py \
            | cat README.md.template - > README.md
        env:
          TIME_API_URL: ${{ secrets.TIME_API_URL }}
          TIME_API_KEY: ${{ secrets.TIME_API_KEY }}

      - name: Push to source
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch origin source || true

          git checkout source || git checkout -b source
          mv README.temp README.md

          git add -A
          git commit -m "Build #$GITHUB_RUN_ID" && git push || true
