name: Build README

on:
  push:
    branches:
      - 'source'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build README
        run: |
          curl -X GET "$TIME_API_URL" -H "Authorization: Basic $TIME_API_KEY" \
            | jq -r '.languages[] | [.key, .total] | @csv' \
            | sed 's/"//g' \
            | python3 process.py \
            | cat README.md -
        env:
          TIME_API_URL: ${{ secrets.TIME_API_URL }}
          TIME_API_KEY: ${{ secrets.TIME_API_KEY }}
